name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && source $HOME/.cargo/env && curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Temporarily remove dist from .gitignore
        run: sed -i '/dist/d' .gitignore

      - name: Build
        run: wasm-pack build --target web --out-dir dist --features wasm

      - name: Initialize gh-pages branch if not exists
        run: |
          git checkout --orphan gh-pages || echo "Branch already exists"
          git reset --hard
          git commit --allow-empty -m "Initial commit"
          git push origin gh-pages || echo "Branch already initialized"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true